services:
  akl-app:
    build: .
    container_name: akl-quotation-system
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-file:/app/data/database.db}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - DB_PATH=/app/data/database.db
    volumes:
      - ./data:/app/data
