import React, { useState, useEffect, useCallback } from 'react';
import { useSession } from 'next-auth/react';
import { InvoiceData, InvoiceItemData } from '@/lib/types';
import { getNextInvoiceNumber } from '@/lib/invoice-number-service';
import ItemRow from '@/components/editor/ItemRow';
import { saveInvoice } from '@/app/actions'; // assume action exists similar to saveQuotation

export default function InvoiceEditor({ onClose }: { onClose?: () => void }) {
  const { data: session } = useSession();
  const isAdmin = !!session?.user?.role?.includes('admin');

  const [invoiceNumber, setInvoiceNumber] = useState<string>('');
  const [date, setDate] = useState<string>('');
  const [dueDate, setDueDate] = useState<string>('');
  const [clientName, setClientName] = useState<string>('');
  const [clientAddress, setClientAddress] = useState<string>('');
  const [taxApplied, setTaxApplied] = useState<boolean>(false);
  const [discountAmount, setDiscountAmount] = useState<number>(0);
  const [downPayment, setDownPayment] = useState<number>(0);
  const [notes, setNotes] = useState<string>('');
  const [items, setItems] = useState<InvoiceItemData[]>([]);

  // Generate invoice number on mount
  useEffect(() => {
    (async () => {
      const num = await getNextInvoiceNumber();
      setInvoiceNumber(num);
    })();
  }, []);

  const handleAddItem = () => {
    setItems(prev => [...prev, { id: Math.random().toString(36).substr(2, 9), description: '', quantity: 0, unitPrice: 0 }]);
  };

  const handleItemChange = (index: number, field: keyof InvoiceItemData, value: any) => {
    setItems(prev => {
      const copy = [...prev];
      // @ts-ignore
      copy[index][field] = value;
      return copy;
    });
  };

  const handleRemoveItem = (index: number) => {
    setItems(prev => prev.filter((_, i) => i !== index));
  };

  const calculateSubtotal = () => {
    return items.reduce((sum, it) => sum + Number(it.quantity) * Number(it.unitPrice), 0);
  };

  const handleSave = async () => {
    if (!isAdmin) return alert('Hanya admin yang dapat menyimpan invoice');
    const subtotal = calculateSubtotal();
    const taxAmount = taxApplied ? subtotal * 0.11 : 0;
    const total = subtotal + taxAmount - discountAmount - downPayment;
    const payload: InvoiceData = {
      id: '', // will be generated by backend
      invoiceNumber,
      date: new Date(date),
      dueDate: dueDate ? new Date(dueDate) : null,
      clientName,
      clientAddress,
      items,
      subtotal,
      taxRate: 0.11,
      taxApplied,
      taxAmount,
      discountAmount,
      downPayment,
      notes,
      total,
      status: 'DRAFT',
    } as any; // backend will adjust types
    const res = await saveInvoice(payload);
    if (res.success) {
      alert('Invoice berhasil disimpan');
      onClose?.();
    } else {
      alert('Gagal menyimpan: ' + res.message);
    }
  };

  return (
    <div className="p-6 bg-white rounded-xl shadow-lg max-w-4xl mx-auto">
      <h2 className="text-2xl font-bold mb-4 text-slate-800">Buat Invoice</h2>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-slate-700">Nomor Invoice</label>
          <input type="text" readOnly value={invoiceNumber} className="mt-1 w-full border rounded p-2 bg-gray-100" />
        </div>
        <div>
          <label className="block text-sm font-medium text-slate-700">Tanggal</label>
          <input type="date" value={date} onChange={e => setDate(e.target.value)} className="mt-1 w-full border rounded p-2" />
        </div>
        <div>
          <label className="block text-sm font-medium text-slate-700">Jatuh Tempo</label>
          <input type="date" value={dueDate} onChange={e => setDueDate(e.target.value)} className="mt-1 w-full border rounded p-2" />
        </div>
        <div>
          <label className="block text-sm font-medium text-slate-700">Klien</label>
          <input type="text" value={clientName} onChange={e => setClientName(e.target.value)} className="mt-1 w-full border rounded p-2" placeholder="Nama Perusahaan / UP" />
        </div>
        <div className="md:col-span-2">
          <label className="block text-sm font-medium text-slate-700">Alamat Klien</label>
          <textarea value={clientAddress} onChange={e => setClientAddress(e.target.value)} className="mt-1 w-full border rounded p-2" rows={2} placeholder="Alamat lengkap" />
        </div>
      </div>

      <section className="mt-6">
        <h3 className="text-lg font-semibold mb-2 text-slate-800">Item</h3>
        {items.map((it, idx) => (
          <ItemRow
            key={it.id}
            index={idx}
            item={it}
            onChange={(field, value) => handleItemChange(idx, field, value)}
            onRemove={() => handleRemoveItem(idx)}
          />
        ))}
        <button type="button" onClick={handleAddItem} className="mt-2 px-4 py-2 bg-emerald-100 text-emerald-800 rounded hover:bg-emerald-200 transition">
          + Tambah Item
        </button>
      </section>

      <section className="mt-6 grid grid-cols-1 md:grid-cols-3 gap-4">
        <div>
          <label className="block text-sm font-medium text-slate-700">PPN 11%</label>
          <input type="checkbox" checked={taxApplied} onChange={e => setTaxApplied(e.target.checked)} className="mt-1" />
        </div>
        <div>
          <label className="block text-sm font-medium text-slate-700">Diskon (Rp)</label>
          <input type="number" value={discountAmount} onChange={e => setDiscountAmount(Number(e.target.value))} className="mt-1 w-full border rounded p-2" />
        </div>
        <div>
          <label className="block text-sm font-medium text-slate-700">Uang Muka (DP)</label>
          <input type="number" value={downPayment} onChange={e => setDownPayment(Number(e.target.value))} className="mt-1 w-full border rounded p-2" />
        </div>
        <div className="md:col-span-3">
          <label className="block text-sm font-medium text-slate-700">Catatan</label>
          <textarea value={notes} onChange={e => setNotes(e.target.value)} className="mt-1 w-full border rounded p-2" rows={2} placeholder="Opsional" />
        </div>
      </section>

      <div className="mt-6 flex justify-end space-x-3">
        <button type="button" onClick={onClose} className="px-4 py-2 bg-slate-200 text-slate-700 rounded hover:bg-slate-300 transition">
          Batal
        </button>
        <button type="button" onClick={handleSave} className="px-4 py-2 bg-emerald-600 text-white rounded hover:bg-emerald-700 transition">
          Simpan Invoice
        </button>
      </div>
    </div>
  );
}
