name: Deploy Apindo App

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  # Gunakan variabel env untuk menyimpan nama image huruf kecil
  IMAGE_NAME: ${{ github.repository }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Memaksa tag menjadi lowercase karena GHCR tidak mengizinkan huruf kapital
          tags: ${{ env.REGISTRY }}/dpdumkm-stack/akl-app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # Masuk ke folder proyek
            cd /var/www/akl-app
            
            # Anti-Error 128 (Git Dubious Ownership)
            git config --global --add safe.directory /var/www/akl-app
            
            # Login ke GHCR di VPS
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Ambil kode terbaru
            git pull origin main
            
            # Pull image terbaru dari GHCR
            docker pull ghcr.io/dpdumkm-stack/akl-app:latest
            
            # Restart container menggunakan image baru
            docker-compose up -d --force-recreate
            
            # Hapus image lama yang sudah tidak terpakai
            docker image prune -f
            
            echo "✨ Deployment Selesai & Berhasil!"
