name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # Masuk ke folder proyek (Anda harus membuat folder ini dulu di VPS)
            # Contoh: cd /var/www/akl-app
            cd /var/www/akl-app
            
            # Ambil kode terbaru
            git pull origin main
            
            # Bangun ulang container (database tetap aman karena pakai volumes)
            docker-compose up -d --build
            
            echo "Deployment Berhasil ke VPS!"
