name: Deploy Apindo App

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: dpdumkm-stack/akl-app
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # Masuk ke folder proyek
            cd /var/www/akl-app
            
            # Anti-Error 128 (Git Dubious Ownership)
            git config --global --add safe.directory /var/www/akl-app
            
            # Ambil kode terbaru (untuk docker-compose.yml)
            git pull origin main
            
            # Login ke GHCR
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # 1. Pull image baru di latar belakang (Pre-fetch)
            echo "🚀 Menarik image terbaru..."
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            
            # 2. Restart container (Switching)
            echo "🔄 Mengganti container ke versi terbaru..."
            docker compose up -d --force-recreate
            
            # 3. Cleanup: Hapus image lama & cache yang tidak terpakai
            echo "🧹 Membersihkan sisa-sisa build lama..."
            docker image prune -f
            
            echo "🔍 Mengecek status container..."
            docker ps
            
            echo "📋 20 Baris Log Terakhir Aplikasi:"
            docker compose logs --tail=20 akl-app
            
            echo "✨ Deployment Berhasil!"
